import type { Edge } from '@xyflow/react';

export const initDemoEdges: Edge[] = [
    {
        id: 'e-n1-n2a',
        source: 'n1-startNode',
        target: 'n2-openOperation',
        targetHandle: 'a',
        type: 'step',
    },
    {
        id: 'e-n2a-n3a',
        source: 'n2-openOperation',
        sourceHandle: 'a',
        target: 'n3-mergeTextOperation',
        targetHandle: 'a',
        type: 'step',
    },
    {
        id: 'e-n5a-n3b',
        source: 'n5-kommuneInput',
        sourceHandle: 'a',
        target: 'n3-mergeTextOperation',
        targetHandle: 'b',
        type: 'step',
    },
    {
        id: 'e-n2b-n3c',
        source: 'n2-openOperation',
        sourceHandle: 'b',
        target: 'n3-mergeTextOperation',
        targetHandle: 'c',
        type: 'step',
    },
    {
        id: 'e-n2e-n3e',
        source: 'n2-openOperation',
        sourceHandle: 'c',
        target: 'n3-mergeTextOperation',
        targetHandle: 'e',
        type: 'step',
    },
    {
        id: 'e-n7a-n3d',
        source: 'n7-gbnrInput',
        sourceHandle: 'a',
        target: 'n3-mergeTextOperation',
        targetHandle: 'd',
        type: 'step',
    },
    {
        id: 'e-n8a-n3f',
        source: 'n8-skraastrekInput',
        sourceHandle: 'a',
        target: 'n3-mergeTextOperation',
        targetHandle: 'f',
        type: 'step',
    },
    {
        id: 'e-n2d-n3g',
        source: 'n2-openOperation',
        sourceHandle: 'd',
        target: 'n3-mergeTextOperation',
        targetHandle: 'g',
        type: 'step',
    },
    {
        id: 'e-n2h-n4a',
        source: 'n2-openOperation',
        sourceHandle: 'h',
        target: 'n4-saksansvarligOperation',
        targetHandle: 'a',
        type: 'step',
    },
    {
        id: 'e-n6a-n10a',
        source: 'n6-createObjectOperation',
        sourceHandle: 'a',
        target: 'n10-arkivOutput',
        type: 'step',
    },
    {
        id: 'e-n3a-n6a',
        source: 'n3-mergeTextOperation',
        sourceHandle: 'a',
        target: 'n6-createObjectOperation',
        targetHandle: 'a',
        type: 'step',
    },
    {
        id: 'e-n3a-n6b',
        source: 'n3-mergeTextOperation',
        sourceHandle: 'a',
        target: 'n6-createObjectOperation',
        targetHandle: 'b',
        type: 'step',
    },
    {
        id: 'e-n4a-n6h',
        source: 'n4-saksansvarligOperation',
        sourceHandle: 'a',
        target: 'n6-createObjectOperation',
        targetHandle: 'e',
        type: 'step',
    },
    {
        id: 'e-n9a-n3h',
        source: 'n9-grunnervervInput',
        sourceHandle: 'a',
        target: 'n3-mergeTextOperation',
        targetHandle: 'h',
        type: 'step',
    },
];
