// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/flow": {
    params: {};
  };
  "/flow/:flowId": {
    params: {
      "flowId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/flow" | "/flow/:flowId";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/flowPage.tsx": {
    id: "routes/flowPage";
    page: "/flow";
  };
  "routes/flowEditor.tsx": {
    id: "routes/flowEditor";
    page: "/flow/:flowId";
  };
};