import type { HandleData, HandleType } from '~/types/handleTypes';
import { DataTypeDefinition } from '~/types/data/datatypes';

export const HMSRegSakHandles = (nodeID: string, handleType: HandleType): HandleData[] => [
    {
        id: `${nodeID}:${handleType}:organisasjonsNavn`,
        typeName: 'organisasjonsNavn',
        label: 'Organisasjonsnavn',
        type: DataTypeDefinition.Text,
        required: true,
    },
    {
        id: `${nodeID}:${handleType}:instansId`,
        typeName: 'instansId',
        label: 'Instans ID',
        type: DataTypeDefinition.Text,
        required: true,
    },
    {
        id: `${nodeID}:${handleType}:organisasjonsNummer`,
        typeName: 'organisasjonsNummer',
        label: 'Organisasjonsnummer',
        type: DataTypeDefinition.Text,
        required: true,
    },
    {
        id: `${nodeID}:${handleType}:prosjektNavn`,
        typeName: 'prosjektNavn',
        label: 'Prosjektnavn',
        type: DataTypeDefinition.Text,
        required: true,
    },
    {
        id: `${nodeID}:${handleType}:hovedLeverandor`,
        typeName: 'hovedLeverandor',
        label: 'Hovedleverandør',
        type: DataTypeDefinition.Text,
        required: true,
    },
    {
        id: `${nodeID}:${handleType}:behandlet`,
        typeName: 'behandlet',
        label: 'Behandlet',
        type: DataTypeDefinition.Text,
        required: true,
    },
    {
        id: `${nodeID}:${handleType}:status`,
        typeName: 'status',
        label: 'Behandlet e-post',
        type: DataTypeDefinition.Text,
        required: true,
    },
    {
        id: `${nodeID}:${handleType}:type`,
        typeName: 'type',
        label: 'Type',
        type: DataTypeDefinition.Text,
        required: true,
    },
    {
        id: `${nodeID}:${handleType}:template`,
        typeName: 'template',
        label: 'Template',
        type: DataTypeDefinition.Text,
        required: true,
    },
    {
        id: `${nodeID}:${handleType}:deviationCode`,
        typeName: 'deviationCode',
        label: 'DeviationCode',
        type: DataTypeDefinition.Text,
        required: true,
    },
    {
        id: `${nodeID}:${handleType}:deviationCodeFU`,
        typeName: 'deviationCodeFU',
        label: 'DeviationCodeFU',
        type: DataTypeDefinition.Text,
        required: true,
    },
    {
        id: `${nodeID}:${handleType}:prosjektId`,
        typeName: 'prosjektId',
        label: 'ProsjektId',
        type: DataTypeDefinition.Text,
        required: true,
    },
    {
        id: `${nodeID}:${handleType}:avdeling`,
        typeName: 'avdeling',
        label: 'Avdeling',
        type: DataTypeDefinition.Text,
        required: true,
    },
    {
        id: `${nodeID}:${handleType}:organisasjonsNummer`,
        typeName: 'organisasjonsNummer',
        label: 'Organisasjonsnummer',
        type: DataTypeDefinition.Text,
        required: true,
    },
    {
        id: `${nodeID}:${handleType}:organisasjonsNummer`,
        typeName: 'organisasjonsNummer',
        label: 'Organisasjonsnummer',
        type: DataTypeDefinition.Text,
        required: true,
    },
    {
        id: `${nodeID}:${handleType}:vedlegg`,
        type: DataTypeDefinition.CollectionObject,
        required: true,
        label: 'Vedlegg',
        typeName: 'vedlegg',
    },
    {
        id: `${nodeID}:${handleType}:hmsregHoveddokument`,
        type: DataTypeDefinition.Object,
        required: true,
        label: 'Hoveddokument',
        typeName: 'hmsregHoveddokument',
    },
];
