import { DataTypeDefinition } from '~/types/data/datatypes';
import type { HandleData } from '~/types/handleTypes';

export const eGrunnervervJournalpostHandles = (
    nodeID: string,
    handleType: 's' | 't'
): HandleData[] => [
    {
        id: `${nodeID}:${handleType}:saksnummer`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Saksnummer',
        typeName: 'saksnummer',
    },
    {
        id: `${nodeID}:${handleType}:tittel`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Tittel',
        typeName: 'tittel',
    },
    {
        id: `${nodeID}:${handleType}:dokumentNavn`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Dokumentnavn',
        typeName: 'dokumentNavn',
    },
    {
        id: `${nodeID}:${handleType}:dokumentDato`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Dokumentdato',
        typeName: 'dokumentDato',
    },
    {
        id: `${nodeID}:${handleType}:forsendelsesmaate`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Forsendelsesmåte',
        typeName: 'forsendelsesmaate',
    },
    {
        id: `${nodeID}:${handleType}:kommunenavn`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Kommunenavn',
        typeName: 'kommunenavn',
    },
    {
        id: `${nodeID}:${handleType}:knr`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Kommunenummer',
        typeName: 'knr',
    },
    {
        id: `${nodeID}:${handleType}:gnr`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Gårdsnummer',
        typeName: 'gnr',
    },
    {
        id: `${nodeID}:${handleType}:bnr`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Bruksnummer',
        typeName: 'bnr',
    },
    {
        id: `${nodeID}:${handleType}:fnr`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Festenummer',
        typeName: 'fnr',
    },
    {
        id: `${nodeID}:${handleType}:snr`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Seksjonsnummer',
        typeName: 'snr',
    },
    {
        id: `${nodeID}:${handleType}:eierforhold`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Eierforhold',
        typeName: 'eierforhold',
    },
    {
        id: `${nodeID}:${handleType}:id`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Id',
        typeName: 'id',
    },
    {
        id: `${nodeID}:${handleType}:maltittel`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Maltittel',
        typeName: 'maltittel',
    },
    {
        id: `${nodeID}:${handleType}:saksbehandlerEpost`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Saksbehandler E-post',
        typeName: 'saksbehandlerEpost',
    },
    {
        id: `${nodeID}:${handleType}:saksbehandler`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Saksbehandler',
        typeName: 'saksbehandler',
    },
    {
        id: `${nodeID}:${handleType}:prosjektnavn`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Prosjektnavn',
        typeName: 'prosjektnavn',
    },
    {
        id: `${nodeID}:${handleType}:mottakere`,
        type: DataTypeDefinition.CollectionObject,
        required: true,
        label: 'Mottakere',
        typeName: 'mottakere',
    },
    {
        id: `${nodeID}:${handleType}:vedlegg`,
        type: DataTypeDefinition.CollectionObject,
        required: true,
        label: 'Vedlegg',
        typeName: 'vedlegg',
    },
];
