import { DataTypeDefinition } from '~/types/data/datatypes';
import type { HandleData } from '~/types/handleTypes';

export const eGrunnervervSaksHandles = (nodeID: string, handleType: 's' | 't'): HandleData[] => [
    {
        id: `${nodeID}:${handleType}:kommunenavn`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Kommunenavn',
        typeName: 'kommunenavn',
    },
    {
        id: `${nodeID}:${handleType}:knr`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Kommunenummer',
        typeName: 'knr',
    },
    {
        id: `${nodeID}:${handleType}:gnr`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Gårdsnummer',
        typeName: 'gnr',
    },
    {
        id: `${nodeID}:${handleType}:bnr`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Bruksnummer',
        typeName: 'bnr',
    },
    {
        id: `${nodeID}:${handleType}:fnr`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Festenummer',
        typeName: 'fnr',
    },
    {
        id: `${nodeID}:${handleType}:snr`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Seksjonsnummer',
        typeName: 'snr',
    },
    {
        id: `${nodeID}:${handleType}:tittel`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Tittel',
        typeName: 'tittel',
    },
    {
        id: `${nodeID}:${handleType}:adresse`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Adresse',
        typeName: 'adresse',
    },
    {
        id: `${nodeID}:${handleType}:eierforholdskode`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Eierforholdskode',
        typeName: 'eierforholdskode',
    },
    {
        id: `${nodeID}:${handleType}:eierforholdsnavn`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Eierforholdsnavn',
        typeName: 'eierforholdsnavn',
    },
    {
        id: `${nodeID}:${handleType}:takstnummer`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Takstnummer',
        typeName: 'takstnummer',
    },
    {
        id: `${nodeID}:${handleType}:prosjektnr`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Prosjektnummer',
        typeName: 'prosjektnr',
    },
    {
        id: `${nodeID}:${handleType}:prosjektnavn`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Prosjektnavn',
        typeName: 'prosjektnavn',
    },
    {
        id: `${nodeID}:${handleType}:saksansvarligEpost`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Saksansvarlig E-post',
        typeName: 'saksansvarligEpost',
    },
    {
        id: `${nodeID}:${handleType}:saksansvarlig`,
        type: DataTypeDefinition.Text,
        required: true,
        label: 'Saksansvarlig',
        typeName: 'saksansvarlig',
    },
    {
        id: `${nodeID}:${handleType}:saksparter`,
        type: DataTypeDefinition.CollectionObject,
        required: true,
        label: 'Saksparter',
        typeName: 'sakspart',
    },
];
