// https://flyt.vigoiks.no/beta/vlfk-no/api/intern/arkiv/kodeverk/klasse?klassifikasjonssystemLink=https%3A%2F%2Fbeta.felleskomponent.no%2Farkiv%2Fnoark%2Fklassifikasjonssystem%2Fsystemid%2FNAMN

export const klasseidOptions = [
    { id: '0064', displayName: '[0064] prøve' },
    { id: '30128722897', displayName: '[30128722897] xiaokang zhou' },
    { id: 'Alver', displayName: '[Alver] Alver' },
    { id: 'Alveråøæ', displayName: '[Alveråøæ] Alveråøæ' },
    { id: 'Askvoll', displayName: '[Askvoll] Askvoll' },
    { id: 'Askøy', displayName: '[Askøy] Askøy' },
    { id: 'Aurland', displayName: '[Aurland] Aurland' },
    { id: 'Austevoll', displayName: '[Austevoll] Austevoll' },
    { id: 'Austrheim', displayName: '[Austrheim] Austrheim' },
    { id: 'Ballestad', displayName: '[Ballestad] Ballestad' },
    { id: 'Bergen', displayName: '[Bergen] Bergen' },
    { id: 'Bjørnafjorden', displayName: '[Bjørnafjorden] Bjørnafjorden' },
    { id: 'BREMANGER', displayName: '[BREMANGER] Bremanger' },
    { id: 'Bømlo', displayName: '[Bømlo] Bømlo' },
    { id: 'Drammen', displayName: '[Drammen] Drammen' },
    { id: 'Eidfjord', displayName: '[Eidfjord] Eidfjord' },
    { id: 'Etne', displayName: '[Etne] Etne kommune' },
    { id: 'FITJAR', displayName: '[FITJAR] FITJAR' },
    { id: 'fjaler', displayName: '[fjaler] fjaler' },
    { id: 'Gloppen', displayName: '[Gloppen] Gloppen' },
    { id: 'Gulen', displayName: '[Gulen] Gulen' },
    { id: 'Høyanger', displayName: '[Høyanger] Høyanger' },
    { id: 'Kinn', displayName: '[Kinn] Kinn' },
    { id: 'KVAM', displayName: '[KVAM] Kvam herad' },
    { id: 'kvinnherad', displayName: '[kvinnherad] Kvinnherad' },
    { id: 'Leikanger', displayName: '[Leikanger] Grunnerverv' },
    { id: 'Luster', displayName: '[Luster] Luster kommune' },
    { id: 'Lærdal', displayName: '[Lærdal] Lærdal' },
    { id: 'Masfjorden', displayName: '[Masfjorden] Masfjorden' },
    { id: 'MOLDE', displayName: '[MOLDE] MOLDE' },
    { id: 'Nord-Odal', displayName: '[Nord-Odal] Nord-Odal' },
    { id: 'OSLO', displayName: '[OSLO] OSLO' },
    { id: 'Osterøy', displayName: '[Osterøy] Osterøy' },
    { id: 'Porsgrunn', displayName: '[Porsgrunn] Porsgrunn' },
    { id: 'Skien kommune', displayName: '[Skien kommune] Skien kommune' },
    { id: 'Skien kommune***PPP', displayName: '[Skien kommune***PPP] Skien kommune***PPP' },
    { id: 'Skien kommune-4.1.1', displayName: '[Skien kommune-4.1.1] Skien kommune-4.1.1' },
    { id: 'Skien kommune-RC1P', displayName: '[Skien kommune-RC1P] Skien kommune-RC1P' },
    { id: 'Sogndal', displayName: '[Sogndal] Sogndal' },
    { id: 'Solund', displayName: '[Solund] Solund kommune' },
    { id: 'Stad', displayName: '[Stad] Stad' },
    { id: 'Stryn', displayName: '[Stryn] Stryn' },
    { id: 'Sunnfjord', displayName: '[Sunnfjord] Sunnfjord' },
    { id: 'Tysnes', displayName: '[Tysnes] Tysnes' },
    { id: 'Ukjent kommunenavn', displayName: '[Ukjent kommunenavn] Ukjent kommunenavn' },
    { id: 'Ullensvang', displayName: '[Ullensvang] Ullensvang' },
    { id: 'Vaksdal', displayName: '[Vaksdal] Vaksdal' },
    { id: 'Vik', displayName: '[Vik] Vik' },
    { id: 'voss', displayName: '[voss] voss ' },
    { id: 'Æåaløæåveråøæ', displayName: '[Æåaløæåveråøæ] Æåaløæåveråøæ' },
    { id: 'Øygarden', displayName: '[Øygarden] Øygarden' },
    { id: 'Årdal', displayName: '[Årdal] Årdal' },
];
